spring:
  application:
    name: rupi-api
  datasource:
    url: ${RUPI_DB_URL:jdbc:mysql://localhost:3306/rupi?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC}
    username: ${RUPI_DB_USERNAME:rupi}
    password: ${RUPI_DB_PASSWORD:}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
  sql:
    init:
      mode: never

server:
  port: ${PORT:8080}
  error:
    include-message: never
